In [1]:
visitors = [150, 200, 180, 220, 190, 250, 170, 1600, 210, 230]

In [5]:
range = max(visitors) - min(visitors)
print(range)

1450


In [12]:
import numpy as np

left_part = visitors[:len(visitors) // 2]
right_part = visitors[len(visitors) // 2:]

q1 = np.median(left_part)
q2 = np.median(visitors)
q3 = np.median(right_part)


print(q1)
print(q2)
print(q3)

190.0
205.0
230.0


In [14]:
IQR = q3 - q1
print(IQR)

40.0


In [16]:
std_vev = np.std(visitors)
print(std_vev)

420.9275472097306


1. Відвідування вебсайту були відносно стабільними протягом цього періоду, за виключенням одного викиду (1600);
2. Типові значення кількості відвідувачів від 190 до 230
3. Так, були екстремальні значення: 1600

In [17]:
#calculating the outlier

import numpy as np


visitors = [150, 200, 180, 220, 190, 250, 170, 1600, 210, 230]

Q1 = np.percentile(visitors, 25)
Q3 = np.percentile(visitors, 75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = [outlier for outlier in visitors if outlier < lower_bound or outlier > upper_bound]
print(outliers)

[1600]
